name: Create Tag

on: push

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Code
       uses: actions/checkout@v2
     - name: Set tag
       id: set-tag
       run:  echo "::set-output name=tag_name::$(sh cut.sh)"
     - name: Output tags
       continue-on-error: true
       run: ${{ steps.set-tag.outputs.tag_name }}
     - name: Create tag
       uses: actions/github-script@v3
       env:
          TAG: ${{ steps.set-tag.outputs.tag_name }}
       with:
          github-token: ${{ github.token }}
          script: |
           // console.log( process.env)
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
             ref: "refs/tags/v${{ steps.set-tag.outputs.tag_name }}",
              sha: context.sha
            })
     - name: Create release
       uses: ncipollo/release-action@v1
       with:
        tag: ${{ steps.set-tag.outputs.tag_name }}
        #commit: GITHUB_REF
        body: "- Testing 2"
        token: ${{ secrets.GITHUB_TOKEN }}