name: Export Events

on:
  push:
    branches:
      - main

jobs:
 log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: 
         php-version: '7.2'
      - name: PHP Work
        id: set-output
        env: 
           COMMITTEXT: "${{ github.event.head_commit.message }}"
        run: |
          OUTPUT=$(php bin/get-commit-message.php)
          echo "::set-output name=release_body::$(cat release.txt)"
# echo "::set-output name=release_body::${OUTPUT}"
# echo ${OUTPUT}
# echo "after"
# exit 1
# php -r "print_r(getenv());"
      - name: Stored ENVs
        run: |
          printenv
#echo "$RELEASEBODY"
      # - name: Set Output ENV
      #   id: set-output
      #   env: 
      #     COMMITTEXT: ${{ github.event.head_commit.message }}
      #   run: echo "::set-output name=release_body::$(php bin/get-commit-message.php)"
      - name: Echo Output ENV
        run: |
          echo "${{ steps.set-output.outputs.release_body }}"
      - name: Create Output
        id: create-output
        env: 
           COMMITTEXT: ${{ github.event.head_commit.message }}
        run: |
          echo "${{  toJson(github.event.commits) }}"
#echo "${{ github.event.commits[0].message }}"
#echo ${{ toJson(github) }}
      - name: Create Output 2
        id: create-output2
        # env: 
        #    COMMITTEXT: ${{ github.event.head_commit.message }}
        run: |
          echo "${{ github.event.commits[0].message }}"
# echo "${{ toJson(github.event.head_commit.message) }}"
# echo "${{ toJson(github.event) }}"
          
#echo "::set-output name=commit_msg::$(sh commit-msg.sh)"

# msg="$(jq '.head_commit.message' $GITHUB_EVENT_PATH)" 
# echo ::set-output name=commit_msg::${msg##*\\n} | tr -d '"'
#msg=${{github.event.head_commit.message}}
      - name: Logging
        run: echo ${{ steps.create-output.outputs.commit_msg }}
#sh commit-msg.sh "${{github.event.head_commit.message}}"
#chmod +x commit-msg.sh
#  echo $(${{github.event.head_commit.message}} | tail -n +3)
# printf -v TEST '%q ' '${{github.event.head_commit.message}}'
### echo $TEST