name: Export Events

on:
  push:
    branches:
      - main

jobs:
 log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Create Output
        id: create-output
        run: |
          msg="$(jq '.head_commit.message' $GITHUB_EVENT_PATH)" 
          echo "::set-output name=commit_msg::${msg##*\\n} | tr -d '"' "

#msg=${{github.event.head_commit.message}}
      - name: Logging
        run: echo ${{ steps.create-output.outputs.commit_msg }}
#sh commit-msg.sh "${{github.event.head_commit.message}}"
#chmod +x commit-msg.sh
#  echo $(${{github.event.head_commit.message}} | tail -n +3)
# printf -v TEST '%q ' '${{github.event.head_commit.message}}'
### echo $TEST