name: Export Events

on:
  push:
    branches:
      - main

jobs:
 log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          sh commit-msg.sh '${{github.event.head_commit.message}}'
#  echo $(${{github.event.head_commit.message}} | tail -n +3)
# printf -v TEST '%q ' '${{github.event.head_commit.message}}'
## echo $TEST